# Generated by Django 2.2.4 on 2024-04-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_show',
            name='description',
            field=models.TextField(default='Cool cool cool'),
            preserve_default=False,
        ),
    ]
